# Generated by Django 6.0.4 on 2026-04-25 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChallengeHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='learning.challenge')),
            ],
            options={
                'ordering': ['challenge__lesson__order', 'challenge__order', 'order'],
                'unique_together': {('challenge', 'order')},
            },
        ),
    ]
